name: CI
on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["master"]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Run linting typescript
        run: npm run lint:ts
      - name: Run linting css
        run: npm run lint:scss
      - name: Run unit test
        run: npm run test:unit
